server:
  port: 8088
  servlet:
    context-path: "/ants"



spring:
  kafka:

    bootstrap-servers: 192.168.15.207:9092,192.168.15.207:9093,192.168.15.207:9094
    producer:
      acks: all
      transaction-id-prefix: tx
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: groupA
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-commit-interval: 1000
      enable-auto-commit: false
      auto-offset-reset: earliest

      listener:
        concurrency: 5
        ack-mode: manual_immediate
        missing-topics-fatal: false




