server:
  port: 8889
  tomcat:
    relaxed-query-chars: '<,>,\,^,`,|,{,},[,]'

ants:
  dirPath: E:/work/filespace/
  pathFlag: "\\"
spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  #解决升版后文件上传问题
  mvc:
    hiddenmethod:
      filter:
        enabled: true