server:
  port: 9991
spring:
  application:
    name: dubbo-samples-provider
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://192.168.16.104:2181
    timeout: 5000
  protocol:
    name: dubbo
    port: 20890
  scan:
    base-packages: com.ants.dubbo.samples
